solutions = [
  { "name"        : "src",
    "url"         : "http://git.chromium.org/chromium/src.git",
    "deps_file"   : ".DEPS.git",
    "custom_deps" : {
      "build": None,
      "chromeos": None,
      "src": None,
      "src/chrome/tools/test/reference_build/chrome": None,
      "src/chrome_frame/tools/test/reference_build/chrome": None,
      "src/chrome/tools/test/reference_build/chrome_linux": None,
      "src/chrome/tools/test/reference_build/chrome_mac": None,
      "src/third_party/hunspell_dictionaries": None,
      "src/third_party/WebKit/LayoutTests": None,
      "src/third_party/WebKit/Source": None,
      "src/third_party/WebKit/Tools.DumpRenderTree": None,
      "src/third_party/WebKit/Tools/gdb": None,
      "src/third_party/WebKit/Tools/Scripts": None,
      "src/third_party/WebKit/WebKitLibraries": None,
      "src/webkit/data/layout_tests/LayoutTests":None,
    },
    "custom_vars":{},
  },
]
